/* Generated By:JavaCC: Do not edit this line. SimpleKWRLProgramParserConstants.java */
package kiwi.service.reasoning.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleKWRLProgramParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRLIT = 6;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int OR = 9;
  /** RegularExpression Id. */
  int NOT = 10;
  /** RegularExpression Id. */
  int THEN = 11;
  /** RegularExpression Id. */
  int TYPE = 12;
  /** RegularExpression Id. */
  int LEFTP = 13;
  /** RegularExpression Id. */
  int RIGHTP = 14;
  /** RegularExpression Id. */
  int INCONSISTENCY = 15;
  /** RegularExpression Id. */
  int URI = 16;
  /** RegularExpression Id. */
  int NS_URI = 17;
  /** RegularExpression Id. */
  int VARIABLE = 18;
  /** RegularExpression Id. */
  int URICONSTRUCTION = 19;
  /** RegularExpression Id. */
  int IDENTIFIER = 20;
  /** RegularExpression Id. */
  int URICHAR = 21;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinString = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\\"\"",
    "\"\\\"\"",
    "<token of kind 7>",
    "\",\"",
    "\";\"",
    "\"not\"",
    "\"->\"",
    "\"^^\"",
    "\"(\"",
    "\")\"",
    "\"inconsistency\"",
    "<URI>",
    "<NS_URI>",
    "<VARIABLE>",
    "\"uri\"",
    "<IDENTIFIER>",
    "<URICHAR>",
    "\":\"",
    "\"@prefix\"",
    "\"<\"",
    "\">\"",
    "\"\\\"\\\"\"",
    "\"@\"",
  };

}
