/* Generated By:JavaCC: Do not edit this line. KiWiQueryParserConstants.java */
package kiwi.service.query.kiwi.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KiWiQueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 5;
  /** RegularExpression Id. */
  int WHERE = 6;
  /** RegularExpression Id. */
  int FORMAT = 7;
  /** RegularExpression Id. */
  int VAR = 8;
  /** RegularExpression Id. */
  int IDENTIFIER = 9;
  /** RegularExpression Id. */
  int LETTER = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 12;
  /** RegularExpression Id. */
  int QUERY = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"SELECT\"",
    "\"WHERE\"",
    "\"FORMAT\"",
    "\"?\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIAL_CHARS>",
    "<QUERY>",
  };

}
